#!/usr/bin/env python

import argparse
import json
import os
import re
import sys
import time

#
# Global
#

CEPHSTATS_LOG_FILE = os.environ.get('CEPHSTATS_LOG_FILE') or \
                     '/var/log/ceph/ceph-stats.{DATE}.log'


#
# Functions
#

def parse_args():
    parser = argparse.ArgumentParser(
        description='process stats from logs generated by ceph-stats'
        )
    parser.add_argument(
        '-d', '--date',
        metavar='YYYY-MM-DD',
        help='date to parse data for',
        default=time.strftime("%F"),
        )
    parser.add_argument(
        'name',
        help='statistics name to look for',
        )
    parser.add_argument(
        'key',
        nargs='+',
        help='key in statistics to look for',
        )
    args = parser.parse_args()
    return args

def logfile(date):
    return CEPHSTATS_LOG_FILE.replace('{DATE}', date)

def main():
    ctx = parse_args()
    f = open(logfile(ctx.date), 'r')
    r = re.compile('^(\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d) \[%s\] \s*(.*)$' % (ctx.name))
    print '#"date" "time"', ' '.join(['"' + x + '"' for x in ctx.key])
    for line in f:
        m = r.match(line)
        if not m:
            continue
        t = m.group(1)
        val = json.loads(m.group(2))
        print t,
        for key in ctx.key:
            v = val
            for k in key.split():
                if k.isdigit():
                    k = int(k)
                try:
                    v = v[k]
                except:
                    v = None
                    break
            print v is None and '-' or v,
        print

main()
